INSTACART_EMAIL: FANCY_CART_ACCT@EMAIL.COM
INSTACART_PASSWD: SUPER_CRYPTO_PWD
SENDER_GMAIL_ID: SENDER_GMAIL_ID
SENDER_GMAIL_PWD: SENDER_GMAIL_PWD
RECEIVER_GMAIL_ID: RECEIVER_GMAIL_ID

SHOPS:
- safeway
- target
- sprouts

OPEN_BROWSER: 1
